### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by viyoriya** [NikkNakk/Brightwork-Theme#19]
![Screenshot from 2019-06-17 09-52-20](https://user-images.githubusercontent.com/32479802/59591272-a9ab5800-90e5-11e9-9708-e631926885b3.png)
1. Please provide ps_warm,cool and pm_warm,cool variables in config.
2. Please provide File browser text color variable in config (i did like this $text_color and used in colours.scss line no 78)
3. File browser hover to change text color
4. File browser (header/top ) radius is still round can we have variable in config looks odd in square 
5. is it possible to provide a square toggle button , check box etc as  assets_square.avg and  provide a variable to pick the assets avg file 

![Screenshot from 2019-06-17 09-45-35](https://user-images.githubusercontent.com/32479802/59591056-3acdff00-90e5-11e9-931c-ba4d5d981070.png)
![Screenshot from 2019-06-17 09-44-26](https://user-images.githubusercontent.com/32479802/59591061-3c97c280-90e5-11e9-9c70-803371693a7f.png)
![Screenshot from 2019-06-17 09-44-48](https://user-images.githubusercontent.com/32479802/59591062-3e618600-90e5-11e9-93d2-6f314523927c.png)

**Comment by NikkNakk** [comment]
Hey! Thanks for all the feedback. I'm going to respond here for now, but I just added some new issue templates for future use. Some of these are more feature requests than issues, so in the future you can tag those as requests to help me keep track of things! Also, if you could try and submit each issue individually and name the post with a short description of the issue so I can better organize what individual issue are present, otherwise I have to open each post when I am trying to track down related issues. 

As for your issues:

1. I added a mix value that allows you modify the warm and cool values, or turn them off completely. These values are just to change the temperatures of colors to create depth and layers. So I can figure out what I might need to add, what were you hoping to be able to do with the values? 

2. Currently I haven't planned on adding that. Right now text colors are handled by what background they are on. I want users to be able to control the theme, but I want to over complicate the config file. I will keep this request in mind, but it will be dependent on interest. 

3. I am working on hover effects. Can you reopen this as a separate issue so I can track it?

4. I think you are referring to the tabs right?  Unfortunately, it would be pretty complex to change the tab corner radius with a single variable, because of how it is handled. I agree that if you want a square theme this creates an issue, and I will try and think of how it could be possible as a config. Currently, the corners on tabs are actually handled by drawing box shadows and different gradients overtop the background to make it look like it has the rounded corners and create the reverse radii on the bottom. GTK doesn't support inverted corner radii, so I had to create the shape.

5. I will have to think about it. The short answer is no, not currently. I could achieve the button shapes for the titlebar (close, minimum, maximum) by drawing the image that is seen when it hovers and using the background property of that image to create the shape of the button. With sliders it would be a bit more complex, especially to keep it consistent across the theme. You could reopen this and tag it a feature request.
